language: python
python:
  - "3.6"      # current default Python on Travis CI
  - "3.7"
  - "3.8"
  - "3.8-dev"  # 3.8 development branch

# Install the codecov pip dependency
install:
  - python3 setup.py install


sudo: required
#services:
#  - mlflow

script:
  #- export PATHONPATH=`pwd`
  - export PYTHONPATH=$PYTHONPATH:$(pwd)
